monotropic:
  base:
    - &BG        '#fffffa'
    - &FG        '#111111'
    - &SELECTION '#fcfaf0'
    - &COMMENT   '#ddddda'
    - &CYAN      '#111111'
    - &GREEN     '#111111'
    - &ORANGE    '#111111'
    - &PINK      '#808080'
    - &PURPLE    '#111111'
    - &RED       '#111111'
    - &YELLOW    '#111111'
  ansi:
    - &COLOR0        '#111111'
    - &COLOR1        '#111111'
    - &COLOR2        '#111111'
    - &COLOR3        '#111111'
    - &COLOR4        '#111111'
    - &COLOR5        '#111111'
    - &COLOR6        '#111111'
    - &COLOR7        '#111111'
    - &COLOR8        '#111111'
    - &COLOR9        '#111111'
    - &COLOR10       '#111111'
    - &COLOR11       '#111111'
    - &COLOR12       '#111111'
    - &COLOR13       '#111111'
    - &COLOR14       '#111111'
    - &COLOR15       '#111111'
  brightOther:
    - &TEMP_QUOTES '#808080'
  other:
    - &LineHighlight '#fcfaf0'
    - &NonText       '#fffffa'
    - &WHITE         '#fffffa'
    - &TAB_DROP_BG   '#ddddda'
    # UI Variants
    - &BGLighter     '#fffffa'
    - &BGLight       '#fffffa'
    - &BGDark        '#fffffa'
    - &BGDarker      '#fffffa'
