name: linter
on:
  pull_request:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.04.05'
      - uses: actions/checkout@v2.3.3
      - name: clj-kondo
        run: clj-kondo --lint scripts test
